export const ProductsConsts = {
    ADD: "PRODUCT_ADD",
    REMOVE: "PRODUCT_REMOVE",
    CHANGE_NAME: "PRODUCT_CHANGE_NAME",
    CHANGE_PRICE: "PRODUCT_CHANGE_PRICE",
    CHANGE_OWNER: "PRODUCT_CHANGE_OWNER"
}